=== MarwanAlsoltany/blend/config/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": [
        "autoload",
        "merge",
        "executables",
        "translations",
        "ansi",
        "quiet",
        "tasks"
    ],
    "properties": {
        "autoload": {
            "title": "Autoload File (PHP autoloader)",
            "description": "The autoload file to use (useful when using PHP callable as task executable).",
            "type": [
                "string",
                "null"
            ]
        },
        "merge": {
            "title": "Merge Config",
            "description": "Whether or not to merge the supplied executables/translations with the default ones.",
            "type": "boolean"
        },
        "executables": {
            "title": "Runner Loadable Tasks",
            "description": "The executables to load as tasks ('key' = executor, 'value' = an array of executables).",
            "type": "object",
            "required": [],
            "properties": {
                "executor": {
                    "title": "Executables",
                    "description": "An array of executables.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "translations": {
            "title": "Runner Task Name Translations",
            "description": "The translations to apply to tasks names.",
            "type": "object",
            "required": [],
            "properties": {
                "from": {
                    "type": "string"
                }
            }
        },
        "ansi": {
            "title": "Runner Output Coloring",
            "description": "Whether or not to turn on ANSI colors for the output.",
            "type": "boolean"
        },
        "quiet": {
            "title": "Runner Output Suppression",
            "description": "Whether or not to turn on the output.",
            "type": "boolean"
        },
        "tasks": {
            "title": "Runner Configurable Tasks",
            "description": "The tasks to add.",
            "type": "object",
            "required": [],
            "patternProperties": {
                ".+": {
                    "title": "Runner Task",
                    "description": "Task definition ('key' = task fallback name, 'value' = task parameters).",
                    "type": "object",
                    "required": [
                        "executor",
                        "executable"
                    ],
                    "properties": {
                        "name": {
                            "title": "Task Name",
                            "description": "If not specified, the key of the containing array will be used instead.",
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "description": {
                            "title": "Task Description",
                            "description": "If not specified a fallback will be used instead.",
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "executor": {
                            "title": "Task Executor",
                            "description": "Valid values are 'shell', 'callback', or any available program executable (for example 'php' is used for PHP).",
                            "type": "string",
                            "enum": [
                                "shell",
                                "callback"
                            ]
                        },
                        "executable": {
                            "title": "Task Executable",
                            "description": "Either a string containing a shell command or a path to an executable file",
                            "type": [
                                "string"
                            ]
                        },
                        "arguments": {
                            "title": "Task Arguments",
                            "description": "A string containing shell command options/arguments.",
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "hidden": {
                            "title": "Task Visibility",
                            "description": "Whether or not to hide the task from being listed.",
                            "type": "boolean"
                        },
                        "disabled": {
                            "title": "Task Availability",
                            "description": "Whether or not to prevent the task from being ran.",
                            "type": "boolean"
                        }
                    }
                }
            }
        }
    }
}

=== MarwanAlsoltany/blend/config/blend.config.json
{
    "autoload": null,
    "merge": true,
    "executables": {
        "php": [
            "./bin/*"
        ]
    },
    "translations": {
        "abc": "xyz"
    },
    "ansi": true,
    "quiet": false,
    "tasks": {
        "some:task": {
            "name": "some:task",
            "description": "Some task",
            "executor": "shell",
            "executable": "ls",
            "arguments": "-lash",
            "hidden": false,
            "disabled": false
        }
    }
}
